// Auto-generated by the i18n codemod — merges every per-file dictionary
// under app/i18n/strings/ into one lookup keyed by "<namespace>.<key>".
// Regenerate by rerunning the codemod, or edit by hand for small additions.
import advisor_page from "./strings/advisor_page";
import cabinet_page from "./strings/cabinet_page";
import calendar_page from "./strings/calendar_page";
import campaign_page from "./strings/campaign_page";
import career_page from "./strings/career_page";
import components_auth_AuthBackground from "./strings/components_auth_AuthBackground";
import components_auth_AuthShell from "./strings/components_auth_AuthShell";
import components_auth_TacticalAuthShell from "./strings/components_auth_TacticalAuthShell";
import components_campaign_CeramahSceneModal from "./strings/components_campaign_CeramahSceneModal";
import components_charts_SeatDonut from "./strings/components_charts_SeatDonut";
import components_layout_AmbientMusic from "./strings/components_layout_AmbientMusic";
import components_layout_Header from "./strings/components_layout_Header";
import components_layout_StatusBar from "./strings/components_layout_StatusBar";
import components_map_StateZoomMap from "./strings/components_map_StateZoomMap";
import components_menu_CreditsModal from "./strings/components_menu_CreditsModal";
import components_ui_LoadingSpinner from "./strings/components_ui_LoadingSpinner";
import components_ui_ShareResultModal from "./strings/components_ui_ShareResultModal";
import components_ui_UpgradeButton from "./strings/components_ui_UpgradeButton";
import elected_page from "./strings/elected_page";
import forgot_password_page from "./strings/forgot_password_page";
import formation_page from "./strings/formation_page";
import government_page from "./strings/government_page";
import kawasan_page from "./strings/kawasan_page";
import load_game_page from "./strings/load_game_page";
import login_page from "./strings/login_page";
import mandate_page from "./strings/mandate_page";
import menu_page from "./strings/menu_page";
import messaging_page from "./strings/messaging_page";
import opposition_page from "./strings/opposition_page";
import polling_page from "./strings/polling_page";
import postmortem_page from "./strings/postmortem_page";
import purchase_confirmation_page from "./strings/purchase_confirmation_page";
import register_page from "./strings/register_page";
import reset_password_page from "./strings/reset_password_page";
import results_page from "./strings/results_page";
import sandbox_page from "./strings/sandbox_page";
import settings_page from "./strings/settings_page";
import setup_page from "./strings/setup_page";
import state__id__page from "./strings/state__id__page";
import stats_page from "./strings/stats_page";
import swearing_in_page from "./strings/swearing_in_page";
import utils_governmentTerms from "./strings/utils_governmentTerms";
import warroom_page from "./strings/warroom_page";

export const dictionary: Record<string, Record<string, { ms: string; en: string }>> = {
  advisor_page,
  cabinet_page,
  calendar_page,
  campaign_page,
  career_page,
  components_auth_AuthBackground,
  components_auth_AuthShell,
  components_auth_TacticalAuthShell,
  components_campaign_CeramahSceneModal,
  components_charts_SeatDonut,
  components_layout_AmbientMusic,
  components_layout_Header,
  components_layout_StatusBar,
  components_map_StateZoomMap,
  components_menu_CreditsModal,
  components_ui_LoadingSpinner,
  components_ui_ShareResultModal,
  components_ui_UpgradeButton,
  elected_page,
  forgot_password_page,
  formation_page,
  government_page,
  kawasan_page,
  load_game_page,
  login_page,
  mandate_page,
  menu_page,
  messaging_page,
  opposition_page,
  polling_page,
  postmortem_page,
  purchase_confirmation_page,
  register_page,
  reset_password_page,
  results_page,
  sandbox_page,
  settings_page,
  setup_page,
  state__id__page,
  stats_page,
  swearing_in_page,
  utils_governmentTerms,
  warroom_page,
};
