// Extracted by i18n codemod from app/components/ui/ShareResultModal.tsx.
export default {
  seats: { ms: "KERUSI", en: "SEATS" },
  majorityTarget: { ms: "SASARAN MAJORITI {dataMajorityTarget}", en: "MAJORITY TARGET {dataMajorityTarget}" },
  nationalSupport: { ms: "SOKONGAN KEBANGSAAN", en: "NATIONAL SUPPORT" },
  campaignDays: { ms: "HARI KEMPEN", en: "CAMPAIGN DAYS" },
  achievements: { ms: "PENCAPAIAN", en: "ACHIEVEMENTS" },
  generatedByMyMandatAMalaysian: { ms: "Dijana oleh MY MANDAT — simulator kempen pilihan raya Malaysia", en: "Generated by MY MANDAT — a Malaysian election campaign simulator" },
  imageDownloaded: { ms: "IMEJ DIMUAT TURUN", en: "IMAGE DOWNLOADED" },
  copyNotSupportedDownloadOnly: { ms: "PENYALINAN TIDAK DISOKONG — MUAT TURUN SAHAJA", en: "COPY NOT SUPPORTED — DOWNLOAD ONLY" },
  imageCopiedPasteAnywhere: { ms: "IMEJ DISALIN — TAMPAL DI MANA-MANA", en: "IMAGE COPIED — PASTE ANYWHERE" },
  copyFailed: { ms: "GAGAL MENYALIN", en: "COPY FAILED" },
  shareResult: { ms: "KONGSI KEPUTUSAN", en: "SHARE RESULT" },
  close: { ms: "Tutup", en: "Close" },
  downloadImage: { ms: "MUAT TURUN IMEJ", en: "DOWNLOAD IMAGE" },
  copyImage: { ms: "SALIN IMEJ", en: "COPY IMAGE" },
};
